Добавление 9 практики
dasha-27/NadyaDasha pull request #12
Opened 2021-05-22 11:55 UTC by dasha-27

2021-05-22 12:29 UTC, dasha-27 commented on pract9.py
> +            self.textEdit3.setText('Неправильные данные')
Похожие функции можно объединить в одну

2021-05-29 17:12 UTC, stanislavlyalin requested changes

2021-05-29 17:12 UTC, stanislavlyalin commented on pract9 (1).py
> +        self.calculation('plus', self.textEdit1.toPlainText(), self.textEdit2.toPlainText())
Можно немного упростить код, если текст из `textEdit1` и `textEdit2` будет извлекаться прямо в методе `calculation`. Тогда передавать эти значения не нужно будет.

2021-05-29 17:12 UTC, stanislavlyalin commented on pract9 (1).py
> +                self.textEdit3.setText(str(a1 + a2))
`textEdit1`, `textEdit2` и `textEdit3` - не самые удачные названия. Лучше переименовать в что-то более осмысленное

2021-05-29 17:12 UTC, stanislavlyalin commented on pract9_7.py
> +        self.e = QFileDialog.getOpenFileNames(self, "D:\\", "D:\\", "'(*.png)'")[0][0]
`self.e` - из названия не понятно назначение поля. Необходимо дать осмысленное имя

2021-05-29 17:12 UTC, stanislavlyalin commented on pract9_7.py
> +sys.exit(app.exec_())
Необходимо проверять, что `__name__ == '__main__'`, как вы делали для калькулятора

2021-05-29 17:12 UTC, stanislavlyalin commented on pract9 (1).py
> +    def minus(self):
Дополнительное задание: вместо строк `plus`, `minus` и т.д. используйте [enum](https://docs.python.org/3/library/enum.html)

2021-05-30 12:29 UTC, merged