Add files via upload
dasha-27/NadyaDasha pull request #2
Opened 2021-03-06 10:55 UTC by dasha-27

Практика 2, проверено, работает

2021-04-01 07:50 UTC, stud111394 requested changes
Все работает.

2021-04-03 12:09 UTC, stanislavlyalin requested changes

2021-04-03 12:09 UTC, stanislavlyalin commented on pract2.py
> +#ЗАДАНИЕ 3
Нет необходимости оставлять закомментированный код. Раскомментируйте его

2021-04-03 12:09 UTC, stanislavlyalin commented on pract2.py
> +# def shift(lst, steps):
Слишком сложно и "не-питоново". Попробуйте сделать как описано в методичке: разделите массив на 2 части, а потом склейте переставленные части в один массив и верните результат.

2021-04-03 12:09 UTC, stanislavlyalin commented on pract2.py
> +#     n1 = int(str(n)[0])
Интересное решение выделить старший разряд :) Преобразуете в строку, а потом первый символ преобразуете обратно в число. Воспользуйтесь операциями целочисленного деления (`//`) и взятия остатка от деления (`%`) для решения этой задачи. Преобразовывать в строку не нужно. Это запутывает код и делает его неэффективным.

2021-04-03 12:09 UTC, stanislavlyalin commented on pract2.py
> +#ЗАДАНИЕ 10
Оформите 10 задание в виде функции

2021-04-15 03:32 UTC, merged