Practice 4
dasha-27/NadyaDasha pull request #7
Opened 2021-04-15 17:27 UTC by dasha-27

Добавление 4 практики

2021-04-15 17:38 UTC, stud111394 requested changes

2021-04-15 17:38 UTC, stud111394 commented on kNN.py
> +        return object_class
Все работает правильно

2021-04-15 17:38 UTC, stud111394 commented on run.py
> +print('/nРезультат классификации: ', monkeys[object_class])
все работает верно

2021-04-26 17:23 UTC, dasha-27 commented on run.py
> +obj = np.array([float(height), float(weight)])
Сделать try?

2021-04-26 17:23 UTC, dasha-27 commented on run.py
> +obj = np.array([float(height), float(weight)])
И сделать аккуратный разделенный код?

2021-04-27 04:12 UTC, stanislavlyalin requested changes

2021-04-27 04:12 UTC, stanislavlyalin commented on kNN.py
> +    new[:16,:2] = X_sub
Указывать конкретные размеры неверно. Матрица `X` может быть и не из 16 строк и 3 столбцов, тогда такой код может привести к ошибке обращения по неправильному индексу. Переменную `new` можно вообще не объявлять, а использовать сразу `X_sub`, предварительно добавив туда `obj`:
```python
X_sub = np.vstack((X_sub, obj))
```
`X_sub` и нужно нормализовать вместе с добавленным объектом, а объект потом можно вытащить обратно так:
```python
obj = X_sub[-1]
```

2021-04-27 04:12 UTC, stanislavlyalin commented on kNN.py
> +    return 0
Получается, что если произошла ошибка, например, размеры массивов не совпадают, функция вернёт расстояние 0, что неверно. Лучше просто выбрасывайте исключение из функции, чтобы вызывающая функция его обрабатывала. Например, так:
```python
except Exception:
    raise 'Ошибка вычисления расстояния'
```

2021-05-10 12:13 UTC, stanislavlyalin requested changes

2021-05-10 12:13 UTC, stanislavlyalin commented on kNN.py
> +    X_sub = X_sub[:16, :2]
Не нужно привязываться к конкретным размерам входной матрицы `X`. В ней может быть и не 16 строк и 3 столбца, а произвольная размерность. Если нужно получить подмножество кроме последней строки, это можно сделать так:
```python
X_sub = X_sub[:-1, :]
```

2021-05-11 17:50 UTC, merged