Добавление 6 практики
dasha-27/NadyaDasha pull request #8
Opened 2021-05-04 19:15 UTC by dasha-27

2021-05-05 09:45 UTC, stud111394 requested changes

2021-05-05 09:45 UTC, stud111394 commented on pract6.py
> +bit_str = input("Количество бит для кодирования от 3 до 7: ")
Можно объединить в одну строчку
bits = int(input("Количество бит для кодирования от 3 до 7: "))

2021-05-10 12:26 UTC, stanislavlyalin requested changes

2021-05-10 12:26 UTC, stanislavlyalin commented on pract6.py
> +        pix_new[t][blue] = y_blue.astype(int)
Блоки кода очень похожи. Попробуйте объединить в функцию

2021-05-11 17:55 UTC, merged